name: Feature Request
description: Suggest a feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! For game design discussions, consider using [GitHub Discussions](https://github.com/colorpulse6/project-chimera/discussions) instead.
  - type: textarea
    id: description
    attributes:
      label: What would you like to see?
      description: Describe the feature or improvement clearly.
      placeholder: Tell us your idea
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why is this useful?
      description: How would this improve the game?
      placeholder: Explain the benefit
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Combat / Battles
        - Exploration / World
        - Story / Dialogue
        - UI / Menus
        - Items / Equipment
        - Performance
        - Other
    validations:
      required: true
