// Bandit Camp - Story dungeon for "The Bandit Problem" quest
// Features: Palisade walls, tents, prison area, leader's tent, hidden cellar
// Background: 1024x1024 at 32px/tile = 32x32

import type { GameMap, NPC, MapEvent, EnemyEncounter, StaticObject } from "../../types";

// Map dimensions — 1024x1024 background at 32px/tile
const WIDTH = 32;
const HEIGHT = 32;

// Ground layer — all tile 0 (background image handles visuals)
function createGroundLayer(): number[][] {
  const ground: number[][] = [];
  for (let y = 0; y < HEIGHT; y++) {
    ground.push(new Array(WIDTH).fill(0));
  }
  return ground;
}

// Create collision layer (true = walkable, false = blocked)
// Generated by collision paint editor for 32x32 grid at 32px tiles
function createCollisionLayer(): boolean[][] {
  const collision: boolean[][] = [];

  for (let y = 0; y < HEIGHT; y++) {
    const row: boolean[] = [];
    for (let x = 0; x < WIDTH; x++) {
      let walkable = false;

      if (y === 4 && x >= 21 && x <= 28) walkable = true;
      if (y >= 5 && y <= 6 && x >= 5 && x <= 29) walkable = true;
      if (y === 7 && x >= 4 && x <= 23) walkable = true;
      if (y === 8 && x >= 3 && x <= 23) walkable = true;
      if (y === 9 && x >= 1 && x <= 30) walkable = true;
      if (y === 10 && x >= 1 && x <= 3) walkable = true;
      if (y === 10 && x >= 7 && x <= 30) walkable = true;
      if (y === 11 && x >= 1 && x <= 3) walkable = true;
      if (y === 11 && x >= 8 && x <= 31) walkable = true;
      if (y >= 12 && y <= 14 && x >= 1 && x <= 31) walkable = true;
      if (y >= 15 && y <= 16 && x >= 1 && x <= 26) walkable = true;
      if (y >= 15 && y <= 16 && x >= 30 && x <= 31) walkable = true;
      if (y === 17 && x >= 1 && x <= 31) walkable = true;
      if (y >= 18 && y <= 19 && x === 1) walkable = true;
      if (y >= 18 && y <= 19 && x >= 8 && x <= 31) walkable = true;
      if (y === 20 && x >= 1 && x <= 31) walkable = true;
      if (y === 21 && x >= 0 && x <= 30) walkable = true;
      if (y === 22 && x >= 1 && x <= 29) walkable = true;
      if (y === 23 && x >= 3 && x <= 27) walkable = true;
      if (y === 24 && x >= 5 && x <= 26) walkable = true;
      if (y === 25 && x >= 13 && x <= 26) walkable = true;
      if (y === 26 && x >= 5 && x <= 8) walkable = true;
      if (y === 26 && x >= 13 && x <= 18) walkable = true;
      if (y === 26 && x === 20) walkable = true;
      if (y === 26 && x >= 22 && x <= 26) walkable = true;
      if (y === 27 && x >= 2 && x <= 19) walkable = true;
      if (y === 27 && x >= 22 && x <= 29) walkable = true;
      if (y === 28 && x >= 0 && x <= 1) walkable = true;
      if (y === 28 && x >= 6 && x <= 29) walkable = true;
      if (y >= 29 && y <= 30 && x >= 0 && x <= 1) walkable = true;
      if (y >= 29 && y <= 30 && x >= 6 && x <= 30) walkable = true;
      if (y === 31 && x >= 0 && x <= 30) walkable = true;

      row.push(walkable);
    }
    collision.push(row);
  }

  return collision;
}

// Create overhead layer (empty — background image handles visuals)
function createOverheadLayer(): number[][] {
  const overhead: number[][] = [];
  for (let y = 0; y < HEIGHT; y++) {
    overhead.push(new Array(WIDTH).fill(-1));
  }
  return overhead;
}

// No static objects — background image renders all structures (tents, cages, bonfire, etc.)
const STATIC_OBJECTS: StaticObject[] = [];

// NPCs - captured villagers (placed at cage positions visible in background)
const NPCS: NPC[] = [
  {
    id: "prisoner_1",
    name: "Captured Farmer",
    x: 24,
    y: 9,
    sprite: "/sprites/characters/villager_prisoner.png",
    facing: "down",
    dialogueId: "prisoner_farmer",
    movement: "static",
  },
  {
    id: "prisoner_2",
    name: "Captured Merchant",
    x: 27,
    y: 9,
    sprite: "/sprites/characters/merchant_prisoner.png",
    facing: "down",
    dialogueId: "prisoner_merchant",
    movement: "static",
  },
  {
    id: "prisoner_3",
    name: "Captured Guard",
    x: 29,
    y: 9,
    sprite: "/sprites/characters/guard_prisoner.png",
    facing: "down",
    dialogueId: "prisoner_guard",
    movement: "static",
  },
];

// Overhead regions — walk-behind occlusion
const OVERHEAD_REGIONS: { x: number; y: number; width: number; height: number; baseY?: number }[] = [
  { x: 23, y: 6, width: 7, height: 1, baseY: 7 },
  { x: 4, y: 8, width: 3, height: 2, baseY: 10 },
  { x: 3, y: 9, width: 1, height: 2, baseY: 11 },
  { x: 7, y: 9, width: 1, height: 2, baseY: 11 },
  { x: 8, y: 10, width: 1, height: 1, baseY: 11 },
  { x: 1, y: 16, width: 7, height: 1, baseY: 17 },
  { x: 2, y: 17, width: 6, height: 1, baseY: 18 },
  { x: 31, y: 20, width: 1, height: 1, baseY: 21 },
  { x: 0, y: 21, width: 1, height: 1, baseY: 22 },
  { x: 29, y: 21, width: 2, height: 1, baseY: 22 },
  { x: 1, y: 22, width: 2, height: 1, baseY: 23 },
  { x: 27, y: 22, width: 3, height: 1, baseY: 23 },
  { x: 3, y: 23, width: 2, height: 1, baseY: 24 },
  { x: 12, y: 23, width: 1, height: 2, baseY: 25 },
  { x: 26, y: 23, width: 2, height: 1, baseY: 24 },
  { x: 5, y: 24, width: 7, height: 1, baseY: 25 },
  { x: 19, y: 24, width: 1, height: 2, baseY: 26 },
  { x: 21, y: 24, width: 6, height: 1, baseY: 25 },
  { x: 21, y: 25, width: 4, height: 1, baseY: 26 },
  { x: 2, y: 27, width: 4, height: 1, baseY: 28 },
];

// Events
const EVENTS: MapEvent[] = [
  // === SAVE POINT (west tent area) ===
  {
    id: "camp_save_point",
    type: "save_point",
    x: 8,
    y: 7,
    data: {
      name: "Bandit Camp - West Tent",
    },
  },

  // === EXIT back to outskirts (south edge, x=13-18 at y=31) ===
  ...Array.from({ length: 6 }, (_, i) => ({
    id: i === 0 ? "camp_exit" : `camp_exit_${i + 1}`,
    type: "teleport" as const,
    x: 13 + i,
    y: 31,
    data: {
      targetMapId: "havenwood_outskirts",
      targetX: 32,
      targetY: 11,
      message: "Leave the bandit camp?",
    },
  })),

  // === PRISONER RESCUE EVENTS ===
  // Two tiles north of each prisoner — player interacts facing south toward cage
  {
    id: "rescue_prisoner_1",
    type: "trigger",
    x: 24,
    y: 7,
    data: {
      triggerType: "rescue",
      flag: "prisoner_1_freed",
      message: "*You break open the rusty cage lock!*\n\nThe farmer stumbles out gratefully.",
      alreadyTriggeredMessage: "The cage is already open.",
      onTrigger: {
        setFlags: ["prisoner_1_freed"],
      },
    },
    triggered: false,
  },
  {
    id: "rescue_prisoner_2",
    type: "trigger",
    x: 27,
    y: 7,
    data: {
      triggerType: "rescue",
      flag: "prisoner_2_freed",
      message: "*The lock gives way with a snap!*\n\nThe merchant is free!",
      alreadyTriggeredMessage: "The cage is already open.",
      onTrigger: {
        setFlags: ["prisoner_2_freed"],
      },
    },
    triggered: false,
  },
  {
    id: "rescue_prisoner_3",
    type: "trigger",
    x: 29,
    y: 7,
    data: {
      triggerType: "rescue",
      flag: "prisoner_3_freed",
      message: "*You wrench the cage door open!*\n\nThe guard staggers out, weak but grateful.",
      alreadyTriggeredMessage: "The cage is already open.",
      onTrigger: {
        setFlags: ["prisoner_3_freed"],
      },
    },
    triggered: false,
  },

  // === ENTER VORN'S TENT (top center — first walkable row below tent) ===
  {
    id: "enter_vorn_tent",
    type: "teleport",
    x: 16,
    y: 5,
    data: {
      targetMapId: "bandit_tent",
      targetX: 5,
      targetY: 7,
      message: "Enter Vorn's tent?",
      requiredFlags: ["prisoner_1_freed", "prisoner_2_freed", "prisoner_3_freed"],
      notMetMessage: "*Loud snoring emanates from inside the tent... Zzzzz...*\n\nPerhaps you should free the prisoners first.",
    },
  },

  // === TREASURE CHESTS ===
  // Supply area (left side)
  {
    id: "supply_chest",
    type: "treasure",
    x: 2,
    y: 12,
    data: {
      items: [
        { itemId: "sanguine_draught", quantity: 3 },
        { itemId: "herb_bundle", quantity: 5 },
      ],
      gold: 150,
    },
    triggered: false,
  },
  // In southwest tent
  {
    id: "tent_chest",
    type: "treasure",
    x: 1,
    y: 18,
    data: {
      items: [
        { itemId: "iron_sword", quantity: 1 },
        { itemId: "leather_armor", quantity: 1 },
      ],
    },
    triggered: false,
  },
  // Near weapon rack (left of center)
  {
    id: "weapon_chest",
    type: "treasure",
    x: 10,
    y: 11,
    data: {
      items: [
        { itemId: "steel_longsword", quantity: 1 },
      ],
      gold: 100,
    },
    triggered: false,
  },

  // === INVESTIGATION POINTS ===
  {
    id: "strange_weapon_examine",
    type: "trigger",
    x: 9,
    y: 10,
    data: {
      triggerType: "examine",
      requiredFlag: "vorn_defeated",
      message: "Among the weapons, you notice something unusual... a metal rod that sparks with energy. This is no ordinary weapon.",
      onTrigger: {
        setFlags: ["saw_lightning_rod"],
      },
    },
  },
];

// Encounter zones - bandit patrols
const ENCOUNTERS: EnemyEncounter[] = [
  // Gate area (south)
  {
    id: "gate_patrol",
    enemies: ["bandit"],
    chance: 0.15,
    zone: { x: 10, y: 21, width: 12, height: 8 },
  },
  // Central camp
  {
    id: "camp_patrol",
    enemies: ["bandit", "bandit"],
    chance: 0.12,
    zone: { x: 10, y: 10, width: 12, height: 10 },
  },
  // Supply area guards (west)
  {
    id: "supply_guards",
    enemies: ["bandit", "rogue_knight"],
    chance: 0.18,
    zone: { x: 5, y: 9, width: 6, height: 8 },
  },
  // Prison guards (east, near cages)
  {
    id: "prison_guards",
    enemies: ["rogue_knight"],
    chance: 0.20,
    zone: { x: 20, y: 11, width: 8, height: 8 },
  },
];

export const BANDIT_CAMP_MAP: GameMap = {
  id: "bandit_camp",
  name: "Bandit Camp",
  width: WIDTH,
  height: HEIGHT,
  tileSize: 32,
  layers: {
    ground: createGroundLayer(),
    collision: createCollisionLayer(),
    overhead: createOverheadLayer(),
  },
  events: EVENTS,
  npcs: NPCS,
  staticObjects: STATIC_OBJECTS,
  overheadRegions: OVERHEAD_REGIONS,
  encounters: ENCOUNTERS,
  connections: [
    {
      id: "to_outskirts",
      targetMapId: "havenwood_outskirts",
      sourcePosition: { x: 15, y: 31 },
      targetPosition: { x: 33, y: 11 },
      type: "edge",
    },
  ],
  background: "/backgrounds/bandit_camp.png",
  ambientColor: "#8b7355",
  music: "danger_theme",
  requiredFlags: ["bandit_camp_discovered"],
};
