// Havenwood Waterfront - Coastal docks district with marsh area
// Background: 1536x1024 at 32px/tile = 48x32

import type { GameMap, NPC, MapEvent, StaticObject } from "../../types";

// Map dimensions (1536x1024 background at 32px/tile)
const WIDTH = 48;
const HEIGHT = 32;

// Create ground layer (rendered via background image)
function createGroundLayer(): number[][] {
  const ground: number[][] = [];
  for (let y = 0; y < HEIGHT; y++) {
    ground.push(new Array(WIDTH).fill(0));
  }
  return ground;
}

// Create collision layer (true = walkable, false = blocked)
// Generated by collision paint editor for 48x32 grid at 32px tiles
function createCollisionLayer(): boolean[][] {
  const collision: boolean[][] = [];

  for (let y = 0; y < HEIGHT; y++) {
    const row: boolean[] = [];
    for (let x = 0; x < WIDTH; x++) {
      let walkable = false;

      if (y === 5 && x >= 14 && x <= 22) walkable = true;
      if (y === 6 && x >= 4 && x <= 15) walkable = true;
      if (y === 7 && x >= 11 && x <= 13) walkable = true;
      if (y === 8 && x >= 12 && x <= 14) walkable = true;
      if (y === 9 && x >= 12 && x <= 15) walkable = true;
      if (y === 10 && x >= 13 && x <= 15) walkable = true;
      if (y === 11 && x >= 13 && x <= 20) walkable = true;
      if (y === 12 && x >= 14 && x <= 25) walkable = true;
      if (y === 13 && x >= 13 && x <= 25) walkable = true;
      if (y === 14 && x >= 6 && x <= 21) walkable = true;
      if (y === 14 && x === 26) walkable = true;
      if (y === 15 && x >= 4 && x <= 22) walkable = true;
      if (y === 16 && x >= 2 && x <= 26) walkable = true;
      if (y === 17 && x >= 1 && x <= 16) walkable = true;
      if (y === 17 && x >= 22 && x <= 29) walkable = true;
      if (y === 18 && x >= 1 && x <= 15) walkable = true;
      if (y === 18 && x >= 25 && x <= 29) walkable = true;
      if (y === 19 && x >= 3 && x <= 11) walkable = true;
      if (y === 20 && x >= 4 && x <= 11) walkable = true;
      if (y === 21 && x >= 5 && x <= 13) walkable = true;
      if (y === 22 && x >= 6 && x <= 13) walkable = true;
      if (y === 23 && x >= 7 && x <= 13) walkable = true;
      if (y === 24 && x >= 10 && x <= 13) walkable = true;
      if (y === 25 && x >= 11 && x <= 13) walkable = true;

      row.push(walkable);
    }
    collision.push(row);
  }

  return collision;
}

// Create overhead layer (empty)
function createOverheadLayer(): number[][] {
  const overhead: number[][] = [];
  for (let y = 0; y < HEIGHT; y++) {
    overhead.push(new Array(WIDTH).fill(-1));
  }
  return overhead;
}

// NPCs at the waterfront
const NPCS: NPC[] = [
  {
    id: "fisherman_reed",
    name: "Old Reed",
    x: 10,
    y: 17,
    sprite: "/sprites/characters/villager.png",
    facing: "down",
    dialogueId: "fisherman_reed_dynamic",
    movement: "static",
  },
  {
    id: "dock_worker_sal",
    name: "Sal",
    x: 20,
    y: 13,
    sprite: "/sprites/characters/villager.png",
    facing: "left",
    dialogueId: "dock_worker_sal",
    movement: "wander",
  },
  {
    id: "marsh_hermit_orin",
    name: "Orin",
    x: 26,
    y: 17,
    sprite: "/sprites/characters/villager.png",
    facing: "up",
    dialogueId: "marsh_hermit_orin",
    movement: "static",
    visibleWhenFlag: "found_mechanism",
  },
];

// Events at the waterfront
const EVENTS: MapEvent[] = [
  // North exit to Village Square (y=5, x=14-22 — top of walkable path)
  ...Array.from({ length: 9 }, (_, i) => ({
    id: i === 0 ? "to_square_north" : `to_square_north_${i + 1}`,
    type: "teleport" as const,
    x: 14 + i,
    y: 5,
    data: {
      targetMapId: "havenwood",
      targetX: 23 + (i % 2),
      targetY: 29,
      message: "Back to Village Square",
    },
  })),
  // Shard chest — hidden at end of marsh path
  {
    id: "chest_shard",
    type: "treasure",
    x: 29,
    y: 18,
    data: {
      items: [{ itemId: "crimson_shard", quantity: 1 }],
      gold: 50,
    },
    triggered: false,
  },
  // Save point at docks
  {
    id: "save_point_dock",
    type: "save_point",
    x: 15,
    y: 15,
    data: {
      message: "The salt air clears your mind.",
      name: "Havenwood Docks",
    },
  },
  // Fishing boat examine — near the boat on the dock edge
  {
    id: "fishing_boat_examine",
    type: "trigger",
    x: 5,
    y: 18,
    data: {
      triggerType: "examine",
      message:
        "A weathered fishing boat named 'The Morning Star'. Its hull is patched in a dozen places but looks seaworthy.",
    },
  },
  // Marsh edge examine — at the entrance to the marsh path
  {
    id: "marsh_edge_examine",
    type: "trigger",
    x: 28,
    y: 17,
    data: {
      triggerType: "examine",
      message:
        "The ground grows soft and waterlogged. Cattails and strange phosphorescent moss line the water's edge. You hear bubbling from somewhere deep in the marsh...",
    },
  },
  // Dock crates examine — on the upper dock platform
  {
    id: "dock_crates_examine",
    type: "trigger",
    x: 24,
    y: 12,
    data: {
      triggerType: "examine",
      message:
        "Supply crates marked with the Lumina family seal. What goods does the noble house receive by sea?",
    },
  },
  // Tide pool examine — on the beach
  {
    id: "tide_pool_examine",
    type: "trigger",
    x: 8,
    y: 22,
    data: {
      triggerType: "examine",
      message:
        "A shallow tide pool trapped between rocks. Small crabs skitter away. Something metallic glints beneath the sand...",
    },
  },
];

// Static objects (none currently)
const STATIC_OBJECTS: StaticObject[] = [];

// Overhead regions — walk-behind occlusion
const OVERHEAD_REGIONS: { x: number; y: number; width: number; height: number; baseY?: number }[] = [
  { x: 4, y: 6, width: 5, height: 1, baseY: 7 },
  { x: 25, y: 13, width: 1, height: 1, baseY: 14 },
  { x: 16, y: 17, width: 1, height: 1, baseY: 18 },
  { x: 23, y: 17, width: 2, height: 1, baseY: 18 },
  { x: 1, y: 18, width: 2, height: 1, baseY: 19 },
  { x: 27, y: 18, width: 1, height: 1, baseY: 19 },
  { x: 3, y: 19, width: 1, height: 1, baseY: 20 },
];

export const HAVENWOOD_WATERFRONT_MAP: GameMap = {
  id: "havenwood_waterfront",
  name: "Havenwood Waterfront",
  width: WIDTH,
  height: HEIGHT,
  tileSize: 32,
  layers: {
    ground: createGroundLayer(),
    collision: createCollisionLayer(),
    overhead: createOverheadLayer(),
  },
  events: EVENTS,
  npcs: NPCS,
  staticObjects: STATIC_OBJECTS,
  overheadRegions: OVERHEAD_REGIONS,
  encounters: [],
  connections: [],
  background: "/backgrounds/havenwood_waterfront.png",
  ambientColor: "#c8dce8",
  music: "peaceful_village",
};
