// Havenwood Residential Lane - Quiet residential district with inn, cottages, and Mira's herb garden

import type { GameMap, NPC, MapEvent, StaticObject } from "../../types";

// Map dimensions (1536x1024 background at 64px/tile)
const WIDTH = 24;
const HEIGHT = 16;

// Create ground layer (fill with 0)
function createGroundLayer(): number[][] {
  const ground: number[][] = [];
  for (let y = 0; y < HEIGHT; y++) {
    ground.push(new Array(WIDTH).fill(0));
  }
  return ground;
}

// Create collision layer (true = walkable, false = blocked)
// Generated by collision paint editor for 24x16 grid at 64px tiles
function createCollisionLayer(): boolean[][] {
  const collision: boolean[][] = [];

  for (let y = 0; y < HEIGHT; y++) {
    const row: boolean[] = [];
    for (let x = 0; x < WIDTH; x++) {
      let walkable = false;

      if (y === 4 && x >= 2 && x <= 8) walkable = true;
      if (y === 4 && x >= 14 && x <= 17) walkable = true;
      if (y === 5 && x === 8) walkable = true;
      if (y === 5 && x >= 10 && x <= 15) walkable = true;
      if (y === 6 && x >= 3 && x <= 15) walkable = true;
      if (y === 6 && x >= 18 && x <= 20) walkable = true;
      if (y === 7 && x >= 0 && x <= 10) walkable = true;
      if (y === 7 && x >= 14 && x <= 20) walkable = true;
      if (y === 8 && x >= 0 && x <= 10) walkable = true;
      if (y === 8 && x >= 12 && x <= 20) walkable = true;
      if (y === 9 && x >= 1 && x <= 18) walkable = true;
      if (y === 10 && x >= 1 && x <= 23) walkable = true;
      if (y === 11 && x >= 2 && x <= 19) walkable = true;
      if (y === 12 && x >= 3 && x <= 19) walkable = true;
      if (y === 13 && x >= 2 && x <= 20) walkable = true;
      if (y >= 14 && y <= 15 && x >= 2 && x <= 22) walkable = true;

      row.push(walkable);
    }
    collision.push(row);
  }

  return collision;
}

// Create overhead layer (fill with -1)
function createOverheadLayer(): number[][] {
  const overhead: number[][] = [];
  for (let y = 0; y < HEIGHT; y++) {
    overhead.push(new Array(WIDTH).fill(-1));
  }
  return overhead;
}

// NPCs in Residential Lane
const NPCS: NPC[] = [
  {
    id: "herbalist_mira",
    name: "Herbalist Mira",
    x: 16,
    y: 9,
    sprite: "/sprites/characters/herbalist.png",
    facing: "down",
    dialogueId: "mira_dynamic",
    movement: "static",
  },
  {
    id: "innkeeper_rowan",
    name: "Innkeeper Rowan",
    x: 5,
    y: 6,
    sprite: "/sprites/characters/villager.png",
    facing: "down",
    dialogueId: "innkeeper_rowan",
    movement: "static",
  },
  {
    id: "old_woman_edith",
    name: "Grandmother Edith",
    x: 10,
    y: 11,
    sprite: "/sprites/characters/villager.png",
    facing: "right",
    dialogueId: "edith_stories",
    movement: "static",
  },
  {
    id: "cat_whiskers",
    name: "Whiskers",
    x: 18,
    y: 12,
    sprite: "/sprites/characters/villager.png",
    facing: "left",
    dialogueId: "cat_meow",
    movement: "wander",
  },
];

// Events in Residential Lane
const EVENTS: MapEvent[] = [
  // Inn entrance (two tiles at y=6)
  {
    id: "havenwood_inn",
    type: "inn",
    x: 3,
    y: 6,
    data: { innName: "The Weary Wanderer", message: "Enter the inn?" },
  },
  {
    id: "havenwood_inn_2",
    type: "inn",
    x: 4,
    y: 6,
    data: { innName: "The Weary Wanderer", message: "Enter the inn?" },
  },
  // West exit to Village Square
  {
    id: "to_square_west",
    type: "teleport",
    x: 0,
    y: 7,
    data: { targetMapId: "havenwood", targetX: 45, targetY: 15, message: "To Village Square" },
  },
  {
    id: "to_square_west_2",
    type: "teleport",
    x: 0,
    y: 8,
    data: { targetMapId: "havenwood", targetX: 45, targetY: 16, message: "To Village Square" },
  },
  // Healing chest in garden shed (near Mira's garden)
  {
    id: "chest_healing",
    type: "treasure",
    x: 19,
    y: 6,
    data: { items: [{ itemId: "sanguine_draught", quantity: 3 }, { itemId: "mithridate", quantity: 1 }] },
    triggered: false,
  },
  // Moonpetal flower 1 — in Mira's garden
  {
    id: "moonpetal_1",
    type: "collectible",
    x: 19,
    y: 12,
    data: { itemId: "moonpetal_flower", quantity: 1, requiredQuest: "herbalists_request", message: "Found a Moonpetal Flower glowing softly in the shade." },
    triggered: false,
  },
  // Moonpetal flower 3 — behind inn in overgrowth
  {
    id: "moonpetal_3",
    type: "collectible",
    x: 3,
    y: 13,
    data: { itemId: "moonpetal_flower", quantity: 1, requiredQuest: "herbalists_request", message: "The final Moonpetal Flower! Mira will be pleased." },
    triggered: false,
  },
  // Herb garden examine
  {
    id: "herb_garden_examine",
    type: "trigger",
    x: 17,
    y: 8,
    data: { triggerType: "examine", message: "Rows of carefully tended herbs: rosemary, sage, nettle, and several plants you don't recognize. The air smells wonderful." },
  },
  // Well examine
  {
    id: "well_examine",
    type: "trigger",
    x: 11,
    y: 8,
    data: { triggerType: "examine", message: "A stone well with a wooden bucket. The water is cool and clean." },
  },
];

// Static objects
const STATIC_OBJECTS: StaticObject[] = [];

// Overhead regions — walk-behind occlusion for buildings, trees, hedges
const OVERHEAD_REGIONS: { x: number; y: number; width: number; height: number; baseY?: number }[] = [
  { x: 2, y: 4, width: 5, height: 1, baseY: 5 },
  { x: 16, y: 4, width: 2, height: 1, baseY: 5 },
  { x: 11, y: 6, width: 3, height: 1, baseY: 7 },
  { x: 16, y: 7, width: 1, height: 3, baseY: 10 },
  { x: 15, y: 8, width: 1, height: 1, baseY: 9 },
  { x: 19, y: 8, width: 2, height: 1, baseY: 9 },
  { x: 1, y: 9, width: 4, height: 1, baseY: 10 },
  { x: 1, y: 10, width: 1, height: 1, baseY: 11 },
  { x: 10, y: 10, width: 1, height: 2, baseY: 12 },
  { x: 17, y: 10, width: 3, height: 1, baseY: 11 },
  { x: 21, y: 10, width: 3, height: 1, baseY: 11 },
  { x: 18, y: 11, width: 1, height: 1, baseY: 12 },
];

export const HAVENWOOD_RESIDENTIAL_MAP: GameMap = {
  id: "havenwood_residential",
  name: "Residential Lane",
  width: WIDTH,
  height: HEIGHT,
  tileSize: 64,
  layers: {
    ground: createGroundLayer(),
    collision: createCollisionLayer(),
    overhead: createOverheadLayer(),
  },
  events: EVENTS,
  npcs: NPCS,
  staticObjects: STATIC_OBJECTS,
  overheadRegions: OVERHEAD_REGIONS,
  encounters: [],
  connections: [],
  background: "/backgrounds/havenwood_residential.png",
  ambientColor: "#e8dcc8",
  music: "peaceful_village",
};
