// Havenwood Village Square - Main hub of the village
// An open plaza with a central fountain, surrounded by buildings and exits to other districts
// Background: 1536x1024 pre-rendered image at 32px/tile -> 48x32 grid

import type { GameMap, NPC, MapEvent, StaticObject } from "../../types";

// Map dimensions - 1536x1024 background at 32px/tile
const WIDTH = 48;
const HEIGHT = 32;

// Ground layer - all tile 0 (cobblestone/grass, background handles visuals)
function createGroundLayer(): number[][] {
  const ground: number[][] = [];
  for (let y = 0; y < HEIGHT; y++) {
    ground.push(new Array(WIDTH).fill(0));
  }
  return ground;
}

// Create collision layer (true = walkable, false = blocked)
// Generated by collision paint editor for 48x32 grid
function createCollisionLayer(): boolean[][] {
  const collision: boolean[][] = [];
  for (let y = 0; y < HEIGHT; y++) {
    const row: boolean[] = [];
    for (let x = 0; x < WIDTH; x++) {
      let walkable = false;

      if (y === 4 && x >= 30 && x <= 31) walkable = true;
      if (y === 5 && x >= 18 && x <= 19) walkable = true;
      if (y === 5 && x >= 28 && x <= 31) walkable = true;
      if (y === 6 && x >= 17 && x <= 19) walkable = true;
      if (y === 6 && x >= 28 && x <= 31) walkable = true;
      if (y === 7 && x >= 14 && x <= 21) walkable = true;
      if (y === 7 && x >= 27 && x <= 31) walkable = true;
      if (y === 8 && x >= 2 && x <= 9) walkable = true;
      if (y === 8 && x >= 14 && x <= 18) walkable = true;
      if (y === 8 && x >= 25 && x <= 32) walkable = true;
      if (y === 9 && x >= 2 && x <= 15) walkable = true;
      if (y === 9 && x >= 24 && x <= 32) walkable = true;
      if (y === 9 && x === 42) walkable = true;
      if (y === 10 && x >= 2 && x <= 15) walkable = true;
      if (y === 10 && x >= 24 && x <= 32) walkable = true;
      if (y === 11 && x >= 2 && x <= 12) walkable = true;
      if (y === 11 && x >= 24 && x <= 37) walkable = true;
      if (y === 12 && x >= 2 && x <= 13) walkable = true;
      if (y === 12 && x === 20) walkable = true;
      if (y === 12 && x >= 23 && x <= 41) walkable = true;
      if (y === 13 && x >= 2 && x <= 41) walkable = true;
      if (y === 14 && x >= 0 && x <= 18) walkable = true;
      if (y === 14 && x >= 26 && x <= 44) walkable = true;
      if (y === 15 && x >= 0 && x <= 16) walkable = true;
      if (y === 15 && x >= 28 && x <= 45) walkable = true;
      if (y === 16 && x === 0) walkable = true;
      if (y === 16 && x >= 2 && x <= 15) walkable = true;
      if (y === 16 && x >= 29 && x <= 45) walkable = true;
      if (y === 17 && x === 0) walkable = true;
      if (y === 17 && x >= 6 && x <= 16) walkable = true;
      if (y === 17 && x >= 30 && x <= 45) walkable = true;
      if (y === 18 && x >= 6 && x <= 18) walkable = true;
      if (y === 18 && x >= 30 && x <= 45) walkable = true;
      if (y === 19 && x >= 5 && x <= 33) walkable = true;
      if (y === 19 && x >= 35 && x <= 47) walkable = true;
      if (y === 20 && x >= 4 && x <= 47) walkable = true;
      if (y >= 21 && y <= 22 && x >= 0 && x <= 47) walkable = true;
      if (y >= 23 && y <= 24 && x >= 0 && x <= 45) walkable = true;
      if (y === 25 && x >= 0 && x <= 42) walkable = true;
      if (y === 26 && x >= 4 && x <= 40) walkable = true;
      if (y === 27 && x >= 6 && x <= 40) walkable = true;
      if (y === 28 && x >= 7 && x <= 42) walkable = true;
      if (y === 29 && x >= 9 && x <= 42) walkable = true;
      if (y === 30 && x >= 8 && x <= 43) walkable = true;
      if (y === 31 && x >= 6 && x <= 45) walkable = true;

      row.push(walkable);
    }
    collision.push(row);
  }
  return collision;
}

// Create overhead layer (no overhead tiles - background handles visuals)
function createOverheadLayer(): number[][] {
  const overhead: number[][] = [];
  for (let y = 0; y < HEIGHT; y++) {
    overhead.push(new Array(WIDTH).fill(-1));
  }
  return overhead;
}

// Static objects - all objects baked into background
const STATIC_OBJECTS: StaticObject[] = [];

// NPCs in the village square (coordinates for 32px grid)
const NPCS: NPC[] = [
  {
    id: "elder_morris",
    name: "Elder Morris",
    x: 14,
    y: 18,
    sprite: "/sprites/characters/elder.png",
    facing: "down",
    dialogueId: "elder_morris_dynamic",
    movement: "static",
  },
  {
    id: "villager_tom",
    name: "Tom",
    x: 12,
    y: 22,
    sprite: "/sprites/characters/villager.png",
    facing: "right",
    dialogueId: "villager_rumors",
    movement: "wander",
  },
  {
    id: "villager_anna",
    name: "Anna",
    x: 34,
    y: 20,
    sprite: "/sprites/characters/villager.png",
    facing: "left",
    dialogueId: "villager_anna",
    movement: "static",
  },
  {
    id: "town_crier",
    name: "Town Crier",
    x: 20,
    y: 12,
    sprite: "/sprites/characters/villager.png",
    facing: "down",
    dialogueId: "town_crier_havenwood",
    movement: "static",
  },
];

// Events in the village square (coordinates for 32px grid)
const EVENTS: MapEvent[] = [
  // Save point at fountain (south side, walkable)
  {
    id: "save_point_square",
    type: "save_point",
    x: 22,
    y: 19,
    data: { message: "The fountain shimmers with an otherworldly light.", name: "Havenwood Square" },
  },
  // North exit to Estate Road (y=4, x=30-31)
  ...Array.from({ length: 2 }, (_, i) => ({
    id: i === 0 ? "to_estate_road" : `to_estate_road_${i + 1}`,
    type: "teleport" as const,
    x: 30 + i,
    y: 4,
    data: { targetMapId: "havenwood_estate_road", targetX: 9 + i, targetY: 46, message: "To Estate Road" },
  })),
  // East exit to Residential Lane (x=47, y=19-22)
  ...Array.from({ length: 4 }, (_, i) => ({
    id: i === 0 ? "to_residential" : `to_residential_${i + 1}`,
    type: "teleport" as const,
    x: 47,
    y: 19 + i,
    data: { targetMapId: "havenwood_residential", targetX: 1, targetY: i < 2 ? 7 : 8, message: "To Residential Lane" },
  })),
  // South exit to Waterfront (y=31, x=9-34)
  ...Array.from({ length: 26 }, (_, i) => ({
    id: i === 0 ? "to_waterfront" : `to_waterfront_${i + 1}`,
    type: "teleport" as const,
    x: 9 + i,
    y: 31,
    data: { targetMapId: "havenwood_waterfront", targetX: 14, targetY: 6, message: "To the Waterfront" },
  })),
  // West exit to Market Row (x=0, y=21-22)
  ...Array.from({ length: 2 }, (_, i) => ({
    id: i === 0 ? "to_market_row" : `to_market_row_${i + 1}`,
    type: "teleport" as const,
    x: 0,
    y: 21 + i,
    data: { targetMapId: "havenwood_market", targetX: 22, targetY: 7 + i, message: "To Market Row" },
  })),
  // Tavern entrance (x=36, y=11)
  {
    id: "tavern_entrance",
    type: "teleport",
    x: 36,
    y: 11,
    data: { targetMapId: "rusted_cog_tavern", targetX: 7, targetY: 10, message: "Enter The Rusted Cog tavern?" },
  },
  // Notice board (near tavern)
  {
    id: "notice_board",
    type: "trigger",
    x: 35,
    y: 11,
    data: { triggerType: "examine", message: "A notice board hangs outside the tavern. Various job postings and warnings are pinned to it. One note mentions 'strange lights in the ruins at night.'" },
  },
  // Fountain examine (west side of fountain, walkable)
  {
    id: "fountain_examine",
    type: "trigger",
    x: 18,
    y: 14,
    data: { triggerType: "examine", message: "A weathered stone fountain stands at the heart of the village. Water trickles gently from a carved fish spout. Coins glint at the bottom — wishes from hopeful villagers." },
  },
  // Secret item hidden behind trees in the upper-left corner
  {
    id: "secret_chest_square",
    type: "treasure",
    x: 2,
    y: 4,
    data: { items: [{ itemId: "sanguine_draught", quantity: 2 }], gold: 150 },
    triggered: false,
  },
];

// Overhead regions — background portions re-drawn on top of characters for "walk-behind" occlusion
const OVERHEAD_REGIONS: { x: number; y: number; width: number; height: number; baseY?: number }[] = [
  { x: 31, y: 4, width: 1, height: 5, baseY: 9 },
  { x: 18, y: 5, width: 2, height: 3, baseY: 8 },
  { x: 17, y: 6, width: 1, height: 3, baseY: 9 },
  { x: 20, y: 7, width: 1, height: 1, baseY: 8 },
  { x: 18, y: 8, width: 1, height: 1, baseY: 9 },
  { x: 13, y: 10, width: 3, height: 1, baseY: 11 },
  { x: 12, y: 11, width: 1, height: 1, baseY: 12 },
  { x: 19, y: 13, width: 7, height: 1, baseY: 14 },
  { x: 16, y: 14, width: 3, height: 1, baseY: 15 },
  { x: 26, y: 14, width: 2, height: 1, baseY: 15 },
  { x: 0, y: 15, width: 3, height: 1, baseY: 16 },
  { x: 16, y: 15, width: 1, height: 1, baseY: 16 },
  { x: 2, y: 16, width: 2, height: 1, baseY: 17 },
  { x: 14, y: 16, width: 1, height: 2, baseY: 18 },
  { x: 34, y: 18, width: 1, height: 1, baseY: 19 },
  { x: 44, y: 21, width: 2, height: 4, baseY: 25 },
  { x: 0, y: 23, width: 3, height: 3, baseY: 26 },
  { x: 3, y: 24, width: 1, height: 2, baseY: 26 },
  { x: 43, y: 24, width: 1, height: 1, baseY: 25 },
  { x: 4, y: 25, width: 3, height: 2, baseY: 27 },
  { x: 40, y: 25, width: 3, height: 1, baseY: 26 },
  { x: 7, y: 26, width: 3, height: 3, baseY: 29 },
  { x: 39, y: 26, width: 2, height: 2, baseY: 28 },
  { x: 6, y: 27, width: 1, height: 1, baseY: 28 },
  { x: 10, y: 27, width: 1, height: 2, baseY: 29 },
];

export const HAVENWOOD_SQUARE_MAP: GameMap = {
  id: "havenwood",
  name: "Havenwood Village",
  width: WIDTH,
  height: HEIGHT,
  tileSize: 32,
  layers: {
    ground: createGroundLayer(),
    collision: createCollisionLayer(),
    overhead: createOverheadLayer(),
  },
  events: EVENTS,
  npcs: NPCS,
  staticObjects: STATIC_OBJECTS,
  encounters: [],
  connections: [],
  overheadRegions: OVERHEAD_REGIONS,
  background: "/backgrounds/havenwood_square.png",
  ambientColor: "#f4e4c1",
  music: "peaceful_village",
};
