// Havenwood Market Row - Bustling market district west of the Village Square
// Features: Shop facades, market stalls, guardhouse, winding paths between vendors
// Background: 1536x1024 at 32px/tile = 48x32

import type { GameMap, NPC, MapEvent, StaticObject } from "../../types";

// Map dimensions — 1536x1024 background at 32px/tile
const WIDTH = 48;
const HEIGHT = 32;

// Ground layer — all tile 0 (background image handles visuals)
function createGroundLayer(): number[][] {
  const ground: number[][] = [];
  for (let y = 0; y < HEIGHT; y++) {
    ground.push(new Array(WIDTH).fill(0));
  }
  return ground;
}

// Create collision layer (true = walkable, false = blocked)
// Generated by collision paint editor for 48x32 grid at 32px tiles
function createCollisionLayer(): boolean[][] {
  const collision: boolean[][] = [];

  for (let y = 0; y < HEIGHT; y++) {
    const row: boolean[] = [];
    for (let x = 0; x < WIDTH; x++) {
      let walkable = false;

      if (y === 2 && x >= 39 && x <= 41) walkable = true;
      if (y === 3 && x >= 37 && x <= 41) walkable = true;
      if (y === 4 && x >= 31 && x <= 41) walkable = true;
      if (y === 5 && x >= 28 && x <= 33) walkable = true;
      if (y === 5 && x >= 36 && x <= 41) walkable = true;
      if (y === 6 && x >= 26 && x <= 29) walkable = true;
      if (y === 6 && x >= 36 && x <= 41) walkable = true;
      if (y === 7 && x >= 24 && x <= 27) walkable = true;
      if (y === 7 && x >= 35 && x <= 41) walkable = true;
      if (y === 8 && x >= 22 && x <= 25) walkable = true;
      if (y === 8 && x >= 34 && x <= 42) walkable = true;
      if (y === 9 && x >= 16 && x <= 24) walkable = true;
      if (y === 9 && x >= 33 && x <= 42) walkable = true;
      if (y === 10 && x >= 13 && x <= 23) walkable = true;
      if (y === 10 && x >= 30 && x <= 42) walkable = true;
      if (y === 11 && x >= 11 && x <= 21) walkable = true;
      if (y === 11 && x >= 30 && x <= 42) walkable = true;
      if (y === 12 && x >= 10 && x <= 20) walkable = true;
      if (y === 12 && x >= 29 && x <= 42) walkable = true;
      if (y === 13 && x === 5) walkable = true;
      if (y === 13 && x >= 7 && x <= 18) walkable = true;
      if (y === 13 && x >= 28 && x <= 43) walkable = true;
      if (y === 14 && x >= 2 && x <= 17) walkable = true;
      if (y === 14 && x >= 27 && x <= 43) walkable = true;
      if (y === 15 && x >= 2 && x <= 16) walkable = true;
      if (y === 15 && x >= 25 && x <= 43) walkable = true;
      if (y === 16 && x >= 0 && x <= 13) walkable = true;
      if (y === 16 && x >= 23 && x <= 40) walkable = true;
      if (y === 17 && x >= 0 && x <= 10) walkable = true;
      if (y === 17 && x >= 20 && x <= 38) walkable = true;
      if (y === 18 && x >= 0 && x <= 8) walkable = true;
      if (y === 18 && x === 10) walkable = true;
      if (y === 18 && x >= 18 && x <= 38) walkable = true;
      if (y === 19 && x >= 0 && x <= 7) walkable = true;
      if (y === 19 && x === 10) walkable = true;
      if (y === 19 && x === 12) walkable = true;
      if (y === 19 && x >= 17 && x <= 30) walkable = true;
      if (y === 20 && x >= 0 && x <= 7) walkable = true;
      if (y === 20 && x >= 17 && x <= 29) walkable = true;
      if (y >= 21 && y <= 22 && x >= 0 && x <= 29) walkable = true;
      if (y === 23 && x >= 1 && x <= 29) walkable = true;
      if (y === 23 && x >= 34 && x <= 38) walkable = true;
      if (y === 24 && x >= 10 && x <= 30) walkable = true;
      if (y === 24 && x >= 34 && x <= 38) walkable = true;
      if (y === 25 && x >= 10 && x <= 38) walkable = true;
      if (y === 26 && x >= 10 && x <= 39) walkable = true;
      if (y === 27 && x >= 9 && x <= 41) walkable = true;
      if (y === 28 && x >= 8 && x <= 41) walkable = true;
      if (y === 29 && x >= 3 && x <= 41) walkable = true;
      if (y === 29 && x === 45) walkable = true;
      if (y === 30 && x >= 2 && x <= 47) walkable = true;
      if (y === 31 && x >= 0 && x <= 47) walkable = true;

      row.push(walkable);
    }
    collision.push(row);
  }

  return collision;
}

// Create overhead layer (empty — background image handles visuals)
function createOverheadLayer(): number[][] {
  const overhead: number[][] = [];
  for (let y = 0; y < HEIGHT; y++) {
    overhead.push(new Array(WIDTH).fill(-1));
  }
  return overhead;
}

// No static objects — background image renders all structures
const STATIC_OBJECTS: StaticObject[] = [];

// Overhead regions — walk-behind occlusion
const OVERHEAD_REGIONS: { x: number; y: number; width: number; height: number; baseY?: number }[] = [
  { x: 32, y: 4, width: 2, height: 2, baseY: 6 },
  { x: 29, y: 5, width: 3, height: 1, baseY: 6 },
  { x: 27, y: 6, width: 3, height: 1, baseY: 7 },
  { x: 25, y: 7, width: 3, height: 1, baseY: 8 },
  { x: 40, y: 7, width: 2, height: 5, baseY: 12 },
  { x: 24, y: 8, width: 2, height: 1, baseY: 9 },
  { x: 39, y: 8, width: 1, height: 5, baseY: 13 },
  { x: 42, y: 8, width: 1, height: 2, baseY: 10 },
  { x: 22, y: 9, width: 3, height: 1, baseY: 10 },
  { x: 38, y: 9, width: 1, height: 4, baseY: 13 },
  { x: 19, y: 10, width: 5, height: 1, baseY: 11 },
  { x: 18, y: 11, width: 4, height: 1, baseY: 12 },
  { x: 37, y: 11, width: 1, height: 7, baseY: 18 },
  { x: 15, y: 12, width: 6, height: 1, baseY: 13 },
  { x: 40, y: 12, width: 1, height: 3, baseY: 15 },
  { x: 13, y: 13, width: 6, height: 1, baseY: 14 },
  { x: 36, y: 13, width: 1, height: 5, baseY: 18 },
  { x: 41, y: 13, width: 1, height: 1, baseY: 14 },
  { x: 9, y: 14, width: 7, height: 1, baseY: 15 },
  { x: 35, y: 14, width: 1, height: 4, baseY: 18 },
  { x: 38, y: 14, width: 2, height: 2, baseY: 16 },
  { x: 9, y: 15, width: 1, height: 3, baseY: 18 },
  { x: 11, y: 15, width: 6, height: 1, baseY: 16 },
  { x: 13, y: 16, width: 1, height: 1, baseY: 17 },
  { x: 34, y: 16, width: 1, height: 2, baseY: 18 },
  { x: 38, y: 16, width: 1, height: 1, baseY: 17 },
  { x: 33, y: 18, width: 1, height: 1, baseY: 19 },
];

// NPCs in Market Row
const NPCS: NPC[] = [
  {
    id: "merchant_aldric",
    name: "Merchant Aldric",
    x: 16,
    y: 14,
    sprite: "/sprites/characters/merchant.png",
    facing: "down",
    dialogueId: "merchant_aldric_dynamic",
    movement: "static",
    hiddenWhenFlag: "helped_aldric",
  },
  {
    id: "guard_captain_bren",
    name: "Captain Bren",
    x: 6,
    y: 16,
    sprite: "/sprites/characters/guard_captain_bren.png",
    facing: "right",
    dialogueId: "bren_dynamic",
    movement: "static",
  },
  {
    id: "market_vendor_fruit",
    name: "Frida",
    x: 15,
    y: 21,
    sprite: "/sprites/characters/frida.png",
    facing: "down",
    dialogueId: "vendor_fruit",
    movement: "static",
    scale: 1.0,
  },
  {
    id: "market_vendor_cloth",
    name: "Weaver Holt",
    x: 25,
    y: 20,
    sprite: "/sprites/characters/weaver_holt.png",
    facing: "left",
    dialogueId: "vendor_cloth",
    movement: "static",
    scale: 1.0,
  },
  {
    id: "market_child",
    name: "Street Urchin",
    x: 38,
    y: 24,
    sprite: "/sprites/characters/street_urchin.png",
    facing: "up",
    dialogueId: "market_child_dialogue",
    movement: "wander",
    scale: 0.85,
  },
];

// Events in Market Row
const EVENTS: MapEvent[] = [
  // === ALDRIC'S SHOP ENTRANCE (y=10: x=13-23 walkable) ===
  {
    id: "aldric_shop_entrance",
    type: "shop",
    x: 18,
    y: 10,
    data: { shopId: "aldric_provisions", message: "Enter Aldric's Provisions?" },
  },

  // === East exit to Village Square (x=43, y=13-14 — rightmost walkable) ===
  {
    id: "to_square_east",
    type: "teleport",
    x: 43,
    y: 13,
    data: { targetMapId: "havenwood", targetX: 2, targetY: 15, message: "To Village Square" },
  },
  {
    id: "to_square_east_2",
    type: "teleport",
    x: 43,
    y: 14,
    data: { targetMapId: "havenwood", targetX: 2, targetY: 15, message: "To Village Square" },
  },

  // === West exit to Outskirts (x=0, y=16-17 walkable) ===
  ...Array.from({ length: 2 }, (_, i) => ({
    id: i === 0 ? "to_outskirts" : `to_outskirts_${i + 1}`,
    type: "teleport" as const,
    x: 0,
    y: 16 + i,
    data: { targetMapId: "havenwood_outskirts", targetX: 17, targetY: 23, message: "Travel to the Havenwood Outskirts?" },
  })),

  // === South exit (y=31: x=0-47 — bottom edge) ===
  ...Array.from({ length: 10 }, (_, i) => ({
    id: i === 0 ? "to_south" : `to_south_${i + 1}`,
    type: "teleport" as const,
    x: 15 + i,
    y: 31,
    data: { targetMapId: "havenwood", targetX: 2, targetY: 15, message: "To Village Square" },
  })),

  // === Weapon chest (y=6: x=36-41 walkable) ===
  {
    id: "chest_weapon",
    type: "treasure",
    x: 41,
    y: 6,
    data: { items: [{ itemId: "steel_longsword", quantity: 1 }], gold: 100 },
    triggered: false,
  },

  // === Moonpetal flower 2 (y=24: x=34-38 walkable) ===
  {
    id: "moonpetal_2",
    type: "collectible",
    x: 36,
    y: 24,
    data: { itemId: "moonpetal_flower", quantity: 1, requiredQuest: "herbalists_request", message: "A delicate Moonpetal Flower\u2014its petals shimmer like captured starlight." },
    triggered: false,
  },

  // === Guardhouse examine (y=13: x=5 single walkable tile near guardhouse) ===
  {
    id: "guardhouse_examine",
    type: "trigger",
    x: 5,
    y: 13,
    data: { triggerType: "examine", message: "The guardhouse notice board shows patrol schedules and wanted posters. One poster describes bandit activity along the outskirts road." },
  },

  // === Fruit stall examine (y=11: x=11-21 walkable, near Frida) ===
  {
    id: "fruit_stall_examine",
    type: "trigger",
    x: 14,
    y: 11,
    data: { triggerType: "examine", message: "Baskets overflow with sun-ripened apples, plums, and strange blue berries you don't recognize. A chalk board reads: 'Fresh today!'" },
  },
];

export const HAVENWOOD_MARKET_MAP: GameMap = {
  id: "havenwood_market",
  name: "Market Row",
  width: WIDTH,
  height: HEIGHT,
  tileSize: 32,
  layers: {
    ground: createGroundLayer(),
    collision: createCollisionLayer(),
    overhead: createOverheadLayer(),
  },
  events: EVENTS,
  npcs: NPCS,
  staticObjects: STATIC_OBJECTS,
  overheadRegions: OVERHEAD_REGIONS,
  encounters: [],
  connections: [
    {
      id: "to_square",
      targetMapId: "havenwood",
      sourcePosition: { x: 43, y: 13 },
      targetPosition: { x: 2, y: 15 },
      type: "edge",
    },
    {
      id: "to_outskirts",
      targetMapId: "havenwood_outskirts",
      sourcePosition: { x: 0, y: 16 },
      targetPosition: { x: 17, y: 23 },
      type: "edge",
    },
  ],
  background: "/backgrounds/havenwood_market.png",
  ambientColor: "#f0dca8",
  music: "peaceful_village",
};
