// Havenwood Outskirts - Connecting area between village and wilderness
// Features paths to: Whispering Ruins (north-east), Bandit Camp (east), Havenwood (south)
// Background: 1120x800 at 32px/tile = 35x25

import type { GameMap, NPC, MapEvent, EnemyEncounter, StaticObject } from "../../types";

// Map dimensions — 1120x800 background at 32px/tile
const WIDTH = 35;
const HEIGHT = 25;

// Ground layer — all tile 0 (background image handles visuals)
function createGroundLayer(): number[][] {
  const ground: number[][] = [];
  for (let y = 0; y < HEIGHT; y++) {
    ground.push(new Array(WIDTH).fill(0));
  }
  return ground;
}

// Create collision layer (true = walkable, false = blocked)
// Generated by collision paint editor for 35x25 grid at 32px tiles
function createCollisionLayer(): boolean[][] {
  const collision: boolean[][] = [];

  for (let y = 0; y < HEIGHT; y++) {
    const row: boolean[] = [];
    for (let x = 0; x < WIDTH; x++) {
      let walkable = false;

      // North exit tile
      if (y === 0 && x === 23) walkable = true;
      if (y === 1 && x >= 21 && x <= 24) walkable = true;
      if (y === 2 && x >= 1 && x <= 2) walkable = true;
      if (y === 2 && x >= 9 && x <= 10) walkable = true;
      if (y === 2 && x >= 21 && x <= 24) walkable = true;
      if (y === 3 && x >= 1 && x <= 3) walkable = true;
      if (y === 3 && x >= 6 && x <= 7) walkable = true;
      if (y === 3 && x >= 9 && x <= 11) walkable = true;
      if (y === 3 && x >= 20 && x <= 25) walkable = true;
      if (y === 4 && x >= 1 && x <= 3) walkable = true;
      if (y === 4 && x >= 6 && x <= 14) walkable = true;
      if (y === 4 && x === 17) walkable = true;
      if (y === 4 && x >= 19 && x <= 33) walkable = true;
      if (y === 5 && x >= 1 && x <= 3) walkable = true;
      if (y === 5 && x >= 6 && x <= 33) walkable = true;
      if (y === 6 && x >= 1 && x <= 5) walkable = true;
      if (y === 6 && x >= 9 && x <= 19) walkable = true;
      if (y === 6 && x >= 21 && x <= 23) walkable = true;
      if (y === 6 && x >= 25 && x <= 33) walkable = true;
      if (y === 7 && x >= 1 && x <= 8) walkable = true;
      if (y === 7 && x >= 11 && x <= 19) walkable = true;
      if (y === 7 && x >= 21 && x <= 24) walkable = true;
      if (y === 7 && x >= 27 && x <= 29) walkable = true;
      if (y === 7 && x === 32) walkable = true;
      if (y === 8 && x >= 1 && x <= 24) walkable = true;
      if (y === 8 && x === 26) walkable = true;
      if (y === 8 && x === 29) walkable = true;
      if (y === 8 && x === 32) walkable = true;
      if (y === 9 && x >= 1 && x <= 3) walkable = true;
      if (y === 9 && x >= 6 && x <= 26) walkable = true;
      if (y === 9 && x >= 30 && x <= 33) walkable = true;
      if (y === 10 && x === 2) walkable = true;
      if (y === 10 && x >= 8 && x <= 12) walkable = true;
      if (y === 10 && x >= 15 && x <= 29) walkable = true;
      if (y === 10 && x >= 31 && x <= 33) walkable = true;
      if (y === 11 && x >= 8 && x <= 18) walkable = true;
      if (y === 11 && x >= 20 && x <= 33) walkable = true;
      if (y === 12 && x >= 8 && x <= 23) walkable = true;
      if (y === 12 && x >= 25 && x <= 30) walkable = true;
      if (y === 12 && x >= 32 && x <= 33) walkable = true;
      if (y === 13 && x >= 1 && x <= 2) walkable = true;
      if (y === 13 && x >= 6 && x <= 9) walkable = true;
      if (y === 13 && x >= 12 && x <= 14) walkable = true;
      if (y === 13 && x >= 16 && x <= 19) walkable = true;
      if (y === 13 && x >= 24 && x <= 32) walkable = true;
      if (y === 14 && x >= 1 && x <= 2) walkable = true;
      if (y === 14 && x >= 7 && x <= 14) walkable = true;
      if (y === 14 && x >= 16 && x <= 27) walkable = true;
      if (y === 14 && x >= 29 && x <= 30) walkable = true;
      if (y === 15 && x >= 2 && x <= 5) walkable = true;
      if (y === 15 && x >= 9 && x <= 30) walkable = true;
      if (y === 16 && x >= 2 && x <= 8) walkable = true;
      if (y === 16 && x === 11) walkable = true;
      if (y === 16 && x >= 13 && x <= 29) walkable = true;
      if (y === 17 && x >= 1 && x <= 9) walkable = true;
      if (y === 17 && x >= 11 && x <= 27) walkable = true;
      if (y === 18 && x >= 1 && x <= 10) walkable = true;
      if (y === 18 && x >= 12 && x <= 16) walkable = true;
      if (y === 18 && x >= 18 && x <= 24) walkable = true;
      if (y === 18 && x >= 26 && x <= 27) walkable = true;
      if (y === 19 && x >= 3 && x <= 4) walkable = true;
      if (y === 19 && x >= 6 && x <= 11) walkable = true;
      if (y === 19 && x >= 13 && x <= 16) walkable = true;
      if (y === 19 && x >= 18 && x <= 32) walkable = true;
      if (y === 20 && x >= 3 && x <= 12) walkable = true;
      if (y === 20 && x >= 15 && x <= 23) walkable = true;
      if (y === 20 && x >= 26 && x <= 32) walkable = true;
      if (y === 21 && x >= 3 && x <= 18) walkable = true;
      if (y === 21 && x >= 23 && x <= 24) walkable = true;
      if (y === 21 && x === 26) walkable = true;
      if (y === 21 && x >= 31 && x <= 32) walkable = true;
      if (y === 22 && x >= 3 && x <= 6) walkable = true;
      if (y === 22 && x >= 8 && x <= 12) walkable = true;
      if (y === 22 && x >= 15 && x <= 18) walkable = true;
      if (y === 23 && x >= 1 && x <= 10) walkable = true;
      if (y === 23 && x === 12) walkable = true;
      if (y === 23 && x >= 15 && x <= 18) walkable = true;
      if (y === 24 && x >= 12 && x <= 19) walkable = true;

      row.push(walkable);
    }
    collision.push(row);
  }

  return collision;
}

// Create overhead layer (empty — background image handles visuals)
function createOverheadLayer(): number[][] {
  const overhead: number[][] = [];
  for (let y = 0; y < HEIGHT; y++) {
    overhead.push(new Array(WIDTH).fill(-1));
  }
  return overhead;
}

// No static objects — background image renders all structures
const STATIC_OBJECTS: StaticObject[] = [];

// NPCs in outskirts
const NPCS: NPC[] = [
  // Traveling merchant on the road
  {
    id: "pedler",
    name: "Peddler",
    x: 15,
    y: 15,
    sprite: "/sprites/characters/pedler.png",
    facing: "right",
    dialogueId: "peddler_outskirts",
    movement: "wander",
  },
  // Guard patrolling the road (x=16 stays walkable through y=14-20)
  {
    id: "guard",
    name: "Guard",
    x: 16,
    y: 20,
    sprite: "/sprites/characters/guard.png",
    facing: "up",
    dialogueId: "guard_outskirts",
    movement: "patrol",
    patrolPath: [
      { x: 16, y: 20 },
      { x: 16, y: 14 },
      { x: 16, y: 20 },
    ],
  },
];

// Overhead regions — walk-behind occlusion
const OVERHEAD_REGIONS: { x: number; y: number; width: number; height: number; baseY?: number }[] = [
  { x: 1, y: 2, width: 2, height: 2, baseY: 4 },
  { x: 3, y: 3, width: 1, height: 1, baseY: 4 },
  { x: 1, y: 4, width: 1, height: 6, baseY: 10 },
  { x: 24, y: 4, width: 1, height: 2, baseY: 6 },
  { x: 32, y: 5, width: 2, height: 2, baseY: 7 },
  { x: 13, y: 8, width: 1, height: 2, baseY: 10 },
  { x: 14, y: 9, width: 1, height: 1, baseY: 10 },
  { x: 21, y: 10, width: 2, height: 3, baseY: 13 },
  { x: 9, y: 11, width: 4, height: 2, baseY: 13 },
  { x: 32, y: 11, width: 2, height: 2, baseY: 13 },
  { x: 28, y: 12, width: 2, height: 2, baseY: 14 },
  { x: 1, y: 13, width: 2, height: 2, baseY: 15 },
  { x: 27, y: 13, width: 1, height: 1, baseY: 14 },
  { x: 12, y: 14, width: 2, height: 2, baseY: 16 },
  { x: 11, y: 15, width: 1, height: 1, baseY: 16 },
  { x: 1, y: 17, width: 5, height: 2, baseY: 19 },
  { x: 25, y: 17, width: 1, height: 1, baseY: 18 },
  { x: 6, y: 18, width: 1, height: 1, baseY: 19 },
  { x: 3, y: 19, width: 1, height: 5, baseY: 24 },
  { x: 4, y: 20, width: 4, height: 2, baseY: 22 },
  { x: 4, y: 22, width: 3, height: 2, baseY: 24 },
  { x: 1, y: 23, width: 2, height: 1, baseY: 24 },
  { x: 7, y: 23, width: 1, height: 1, baseY: 24 },
];

// Events in outskirts
const EVENTS: MapEvent[] = [
  // === SAVE POINT at shrine (y=7: x=11-19 walkable) ===
  {
    id: "outskirts_save_point",
    type: "save_point",
    x: 18,
    y: 7,
    data: {
      name: "Roadside Shrine",
    },
  },

  // === TELEPORT to Havenwood Market (south exit, y=24: x=12-19 walkable) ===
  ...Array.from({ length: 8 }, (_, i) => ({
    id: i === 0 ? "to_havenwood" : `to_havenwood_${i + 1}`,
    type: "teleport" as const,
    x: 12 + i,
    y: 24,
    data: {
      targetMapId: "havenwood_market",
      targetX: 2,
      targetY: 18,
      message: "Return to Market Row?",
    },
  })),

  // === TELEPORT to Whispering Ruins (north-east exit) ===
  {
    id: "to_ruins",
    type: "teleport",
    x: 23,
    y: 0,
    data: {
      targetMapId: "whispering_ruins",
      targetX: 5,
      targetY: 17,
      message: "Enter the Whispering Ruins?",
    },
  },
  // Additional ruins exit tiles at y=1 (x=21-24 walkable)
  ...Array.from({ length: 4 }, (_, i) => ({
    id: `to_ruins_${i + 2}`,
    type: "teleport" as const,
    x: 21 + i,
    y: 1,
    data: {
      targetMapId: "whispering_ruins",
      targetX: 5,
      targetY: 17,
      message: "Enter the Whispering Ruins?",
    },
  })),

  // === TELEPORT to Bandit Camp (east exit, y=11: x=20-33 walkable) ===
  {
    id: "to_bandit_camp",
    type: "teleport",
    x: 33,
    y: 11,
    data: {
      targetMapId: "bandit_camp",
      targetX: 15,
      targetY: 30,
      message: "The path leads to a suspicious camp...",
      requiredFlag: "bandit_camp_discovered",
      notMetMessage: "The path ahead looks dangerous and unfamiliar. Perhaps Elder Morris or the guards know more about what lies this way.",
    },
  },

  // === TREASURE in watchtower ruins (y=6: x=1-5 walkable) ===
  {
    id: "watchtower_chest",
    type: "treasure",
    x: 5,
    y: 6,
    data: {
      items: [
        { itemId: "sanguine_draught", quantity: 2 },
        { itemId: "antidote_draught", quantity: 1 },
      ],
      gold: 75,
    },
    triggered: false,
  },

  // === COLLECTIBLE at old well (y=7: x=11-19 walkable) ===
  {
    id: "well_item",
    type: "collectible",
    x: 12,
    y: 7,
    data: {
      itemId: "rusty_key",
      quantity: 1,
      message: "You found a rusty key at the bottom of the well. What could it unlock?",
    },
    triggered: false,
  },

  // === EVIDENCE of bandits (y=8: x=1-24 walkable) ===
  {
    id: "bandit_campfire",
    type: "trigger",
    x: 24,
    y: 8,
    data: {
      triggerType: "investigation",
      flag: "found_bandit_evidence",
      message: "The remains of a recent campfire. Someone was watching the road from here...",
      onTrigger: {
        setFlags: ["found_bandit_evidence"],
        dialogue: "campfire_investigation",
      },
    },
    triggered: false,
  },

  // === SIGNPOST interaction (y=11: x=8-18 walkable) ===
  {
    id: "signpost_interaction",
    type: "trigger",
    x: 18,
    y: 11,
    data: {
      triggerType: "examine",
      message: "North: Whispering Ruins (DANGER)\nSouth: Havenwood Village\nEast: Old Mill Road",
    },
  },
];

// Encounter zones - light encounters on the outskirts
const ENCOUNTERS: EnemyEncounter[] = [
  // Wolf packs in grassy areas (west side)
  {
    id: "outskirts_wolves",
    enemies: ["wild_wolf"],
    chance: 0.08,
    zone: { x: 0, y: 10, width: 12, height: 12 },
  },
  // Bandits near eastern path
  {
    id: "outskirts_bandits",
    enemies: ["bandit"],
    chance: 0.10,
    zone: { x: 22, y: 5, width: 12, height: 10 },
  },
  // Mixed encounters near ruins entrance (north-east)
  {
    id: "outskirts_north",
    enemies: ["wild_wolf", "bandit"],
    chance: 0.12,
    zone: { x: 18, y: 0, width: 12, height: 8 },
  },
];

export const HAVENWOOD_OUTSKIRTS_MAP: GameMap = {
  id: "havenwood_outskirts",
  name: "Havenwood Outskirts",
  width: WIDTH,
  height: HEIGHT,
  tileSize: 32,
  layers: {
    ground: createGroundLayer(),
    collision: createCollisionLayer(),
    overhead: createOverheadLayer(),
  },
  events: EVENTS,
  npcs: NPCS,
  staticObjects: STATIC_OBJECTS,
  overheadRegions: OVERHEAD_REGIONS,
  encounters: ENCOUNTERS,
  connections: [
    {
      id: "to_havenwood",
      targetMapId: "havenwood_market",
      sourcePosition: { x: 15, y: 24 },
      targetPosition: { x: 1, y: 9 },
      type: "edge",
    },
    {
      id: "to_ruins",
      targetMapId: "whispering_ruins",
      sourcePosition: { x: 23, y: 0 },
      targetPosition: { x: 5, y: 17 },
      type: "edge",
    },
    {
      id: "to_bandit_camp",
      targetMapId: "bandit_camp",
      sourcePosition: { x: 33, y: 11 },
      targetPosition: { x: 15, y: 30 },
      type: "edge",
    },
  ],
  background: "/backgrounds/havenwood_outskirts.png",
  ambientColor: "#d4c4a8",
  music: "outskirts_theme",
  requiredFlags: ["outskirts_unlocked"],
};
