// Whispering Ruins - First dungeon area with encounters
// Features: Ancient stone ruin over a dark abyss, glowing northern chamber
// Background: 800x640 at 32px/tile = 25x20

import type { GameMap, NPC, MapEvent, EnemyEncounter, StaticObject } from "../../types";

// Map dimensions — 800x640 background at 32px/tile
const WIDTH = 25;
const HEIGHT = 20;

// Ground layer — all tile 0 (background image handles visuals)
function createGroundLayer(): number[][] {
  const ground: number[][] = [];
  for (let y = 0; y < HEIGHT; y++) {
    ground.push(new Array(WIDTH).fill(0));
  }
  return ground;
}

// Create collision layer (true = walkable, false = blocked)
// Generated by collision paint editor for 25x20 grid at 32px tiles
function createCollisionLayer(): boolean[][] {
  const collision: boolean[][] = [];

  for (let y = 0; y < HEIGHT; y++) {
    const row: boolean[] = [];
    for (let x = 0; x < WIDTH; x++) {
      let walkable = false;

      if (y === 2 && x >= 10 && x <= 14) walkable = true;
      if (y === 3 && x >= 7 && x <= 17) walkable = true;
      if (y === 4 && x >= 6 && x <= 19) walkable = true;
      if (y === 5 && x >= 8 && x <= 22) walkable = true;
      if (y === 6 && x >= 2 && x <= 5) walkable = true;
      if (y === 6 && x >= 8 && x <= 15) walkable = true;
      if (y === 7 && x >= 2 && x <= 7) walkable = true;
      if (y === 7 && x >= 10 && x <= 15) walkable = true;
      if (y === 8 && x >= 2 && x <= 6) walkable = true;
      if (y === 8 && x >= 10 && x <= 14) walkable = true;
      if (y === 8 && x >= 18 && x <= 23) walkable = true;
      if (y >= 9 && y <= 10 && x >= 2 && x <= 5) walkable = true;
      if (y >= 9 && y <= 10 && x >= 11 && x <= 13) walkable = true;
      if (y >= 9 && y <= 10 && x >= 20 && x <= 23) walkable = true;
      if (y === 11 && x >= 2 && x <= 6) walkable = true;
      if (y === 11 && x >= 11 && x <= 13) walkable = true;
      if (y === 11 && x >= 20 && x <= 21) walkable = true;
      if (y === 12 && x >= 4 && x <= 15) walkable = true;
      if (y === 12 && x >= 19 && x <= 21) walkable = true;
      if (y === 13 && x >= 7 && x <= 20) walkable = true;
      if (y >= 14 && y <= 15 && x >= 5 && x <= 18) walkable = true;
      if (y === 16 && x >= 5 && x <= 10) walkable = true;
      if (y === 16 && x >= 14 && x <= 19) walkable = true;
      if (y === 17 && x >= 4 && x <= 10) walkable = true;
      if (y === 17 && x === 12) walkable = true;
      if (y === 17 && x >= 14 && x <= 19) walkable = true;
      if (y === 18 && x >= 5 && x <= 18) walkable = true;
      if (y === 19 && x >= 9 && x <= 15) walkable = true;

      row.push(walkable);
    }
    collision.push(row);
  }

  return collision;
}

// Create overhead layer (empty — background image handles visuals)
function createOverheadLayer(): number[][] {
  const overhead: number[][] = [];
  for (let y = 0; y < HEIGHT; y++) {
    overhead.push(new Array(WIDTH).fill(-1));
  }
  return overhead;
}

// No static objects — background image renders all structures
const STATIC_OBJECTS: StaticObject[] = [];

// NPCs in ruins
const NPCS: NPC[] = [
  {
    id: "mysterious_figure",
    name: "???",
    x: 12,
    y: 2,
    sprite: "/sprites/characters/mysterious.png",
    facing: "down",
    dialogueId: "mysterious_intro",
    movement: "static",
  },
];

// Events in ruins
const EVENTS: MapEvent[] = [
  // === SAVE POINT (south area) ===
  {
    id: "ruins_save_point",
    type: "save_point",
    x: 5,
    y: 15,
    data: {
      name: "Ruins Entrance",
    },
  },

  // === EXIT to Havenwood Outskirts (south edge, y=19: x=9-15) ===
  ...Array.from({ length: 7 }, (_, i) => ({
    id: i === 0 ? "outskirts_exit" : `outskirts_exit_${i + 1}`,
    type: "teleport" as const,
    x: 9 + i,
    y: 19,
    data: {
      targetMapId: "havenwood_outskirts",
      targetX: 22,
      targetY: 2,
      message: "Return to the Havenwood Outskirts?",
    },
  })),

  // === TREASURE — west alcove (y=7: x=2-7 walkable) ===
  {
    id: "ruins_chest_1",
    type: "treasure",
    x: 2,
    y: 7,
    data: {
      itemId: "ether",
      quantity: 1,
    },
    triggered: false,
  },

  // === TREASURE — east alcove (y=8: x=18-23 walkable) ===
  {
    id: "ruins_chest_2",
    type: "treasure",
    x: 23,
    y: 8,
    data: {
      itemId: "hi_potion",
      quantity: 1,
    },
    triggered: false,
  },

  // === BOSS BATTLE — System Agent (central chamber) ===
  {
    id: "boss_trigger",
    type: "battle",
    x: 12,
    y: 4,
    data: {
      enemies: ["system_agent"],
      isBoss: true,
      oneTime: true,
    },
    triggered: false,
  },

  // === STRANGER'S CACHE — hidden in glowing northern area ===
  {
    id: "stranger_cache",
    type: "treasure",
    x: 11,
    y: 2,
    data: {
      items: [{ itemId: "observers_token", quantity: 1 }],
      requiredQuest: "the_hooded_stranger",
      questObjective: { questId: "the_hooded_stranger", objectiveId: "find_cache" },
      message: "Hidden behind a panel of glowing tiles, you find a small alcove. Inside rests a strange coin with an unblinking eye symbol. It pulses faintly in your hand...",
    },
    triggered: false,
  },

  // === ENTRANCE TO LOWER RUINS (requires Lyra) ===
  {
    id: "to_lower_ruins",
    type: "teleport",
    x: 12,
    y: 5,
    data: {
      targetMapId: "whispering_ruins_lower",
      targetX: 17,
      targetY: 27,
      message: "Descend deeper into the ruins with Lyra?",
      requiredFlag: "showed_mechanism",
      notMetMessage: "The passage descends into impenetrable darkness. Strange symbols line the walls... You sense this place holds secrets beyond your understanding. Perhaps someone with knowledge of ancient lore could help decipher them.",
    },
  },
];

// Encounter zones in the ruins
const ENCOUNTERS: EnemyEncounter[] = [
  // Western alcoves (y=6-11, x=2-6)
  {
    id: "western_corridor",
    enemies: ["bandit"],
    chance: 0.15,
    zone: { x: 2, y: 6, width: 5, height: 6 },
  },
  // Central chamber (y=3-5, x=6-19)
  {
    id: "central_chamber",
    enemies: ["corrupted"],
    chance: 0.12,
    zone: { x: 6, y: 3, width: 14, height: 10 },
  },
  // Eastern alcoves (y=8-11, x=18-23)
  {
    id: "eastern_corridor",
    enemies: ["corrupted"],
    chance: 0.18,
    zone: { x: 18, y: 8, width: 6, height: 4 },
  },
  // Entrance / south area (y=14-19, x=5-18)
  {
    id: "entrance_path",
    enemies: ["bandit"],
    chance: 0.08,
    zone: { x: 5, y: 14, width: 14, height: 6 },
  },
];

export const WHISPERING_RUINS_MAP: GameMap = {
  id: "whispering_ruins",
  name: "Whispering Ruins",
  width: WIDTH,
  height: HEIGHT,
  tileSize: 32,
  layers: {
    ground: createGroundLayer(),
    collision: createCollisionLayer(),
    overhead: createOverheadLayer(),
  },
  events: EVENTS,
  npcs: NPCS,
  staticObjects: STATIC_OBJECTS,
  encounters: ENCOUNTERS,
  connections: [
    {
      id: "to_outskirts",
      targetMapId: "havenwood_outskirts",
      sourcePosition: { x: 12, y: 19 },
      targetPosition: { x: 22, y: 2 },
      type: "edge",
    },
    {
      id: "to_lower_ruins",
      targetMapId: "whispering_ruins_lower",
      sourcePosition: { x: 12, y: 5 },
      targetPosition: { x: 17, y: 27 },
      type: "stairs",
    },
  ],
  background: "/backgrounds/whispering_ruins.png",
  ambientColor: "#2a2a3d",
  music: "dungeon_mystery",
};
